
def get_fake_data():
    #cached copy of metadata
    return {"random_seed": "c6T4NkT8DKF68G02YsR5CSS6lNeP96GsH5S052/zinphLzkTW",
            "uuid": "35feac83-aa67-4efd-8723-0b6cedf5bcdf",
            "availability_zone": "nova",
            "hostname": "windows-2012.novalocal",
            "launch_index": 0,
            "public_keys": {"key": "ssh-rsa fakekey..Generated by Nova\n"},
            "name": "Windows 2012"
            }


def get_fake_user_data():
    #user defined data
    user_data = {''}


def get_fake_password():
    #password
    password = ''
